apiVersion: v1
kind: ConfigMap
metadata:
  name: go-webhook-config
  namespace: default
data:
  config.yaml: |
    version: 1.0
    worker:
    - remittance-queue: remittance-worker
    - batch:            batch-queue
    - elastic_search:   es-queue
    - webhook:          webhook-worker
    - test: new  
