apiVersion: v1
kind: ConfigMap
metadata:
  name: go-webhook-config
  namespace: default
data:
  config.yaml: |
    version: 1.0
    worker_namespace: "lumen"
    alert_services: "arthur,apollo"
    notification:
      email:
        to: "bikram.dhoju@gmail.com,itsbecram@gmail.com"
        from: "release@arthuronline.co.uk"
        subject: "Arthur Release"
        sender: "ArthurOnline"
        template_path: "/work/email-templates/email.pr.tpl.html"
    worker:
    - remittance-queue: remittance-worker
    - batch:            batch-queue
    - elastic_search:   es-queue
    - webhook:          webhook-worker
