apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-webhook
  name: go-webhook
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-webhook
  template:
    metadata:
      labels:
        app: go-webhook
    spec:
      containers:
        - image: go-webhook:1.0
          imagePullPolicy: Never
          name: go-webhook
          command: ["/usr/local/bin/go-webhook"]
          args:
            - --config
            - /app/config.yaml
          env:
            - name: TLS
              value: "true"
            - name: LOG_LEVEL
              value: "trace"
            - name: LOG_JSON
              value: "false"
          resources:
            requests:
              cpu: 50m
              memory: 32M
            limits:
              cpu: 100m
              memory: 64M
          volumeMounts:
          - name: config
            mountPath: /app
      serviceAccount: go-webhook
      volumes:
      - name: config
        configMap:
          name: go-webhook-config
