---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-webhook
  name: go-webhook
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30100
  selector:
    app: go-webhook
