name: Build test

on:
  push:
    branches-ignore:
      - "main"

  
jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ["8.1.17"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 100
      
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=min
          build-args: |
            "TARGETARCH=amd64"
